export default function getTutorialSteps(t) {
  return [
    {
      id: 'welcome',
      title: t('tutorial:steps.welcome.title'),
      description: t('tutorial:steps.welcome.description'),
      target: '[data-tutorial="header"]',
      position: 'bottom',
      example: t('tutorial:steps.welcome.example'),
    },
    {
      id: 'position-mode',
      title: t('tutorial:steps.positionMode.title'),
      description: t('tutorial:steps.positionMode.description'),
      target: '[data-tutorial="position-mode"]',
      position: 'bottom',
      example: t('tutorial:steps.positionMode.example'),
    },
    {
      id: 'margin-mode',
      title: t('tutorial:steps.marginMode.title'),
      description: t('tutorial:steps.marginMode.description'),
      target: '[data-tutorial="margin-mode"]',
      position: 'bottom',
      example: t('tutorial:steps.marginMode.example'),
    },
    {
      id: 'direction',
      title: t('tutorial:steps.direction.title'),
      description: t('tutorial:steps.direction.description'),
      target: '[data-tutorial="direction"]',
      position: 'bottom',
      example: t('tutorial:steps.direction.example'),
    },
    {
      id: 'order-type',
      title: t('tutorial:steps.orderType.title'),
      description: t('tutorial:steps.orderType.description'),
      target: '[data-tutorial="order-type"]',
      position: 'bottom',
      example: t('tutorial:steps.orderType.example'),
    },
    {
      id: 'entry-price',
      title: t('tutorial:steps.entryPrice.title'),
      description: t('tutorial:steps.entryPrice.description'),
      target: '[data-tutorial="entry-price"]',
      position: 'bottom',
    },
    {
      id: 'leverage',
      title: t('tutorial:steps.leverage.title'),
      description: t('tutorial:steps.leverage.description'),
      target: '[data-tutorial="leverage"]',
      position: 'bottom',
      example: t('tutorial:steps.leverage.example'),
    },
    {
      id: 'size',
      title: t('tutorial:steps.size.title'),
      description: t('tutorial:steps.size.description'),
      target: '[data-tutorial="size"]',
      position: 'top',
      example: t('tutorial:steps.size.example'),
    },
    {
      id: 'stop-loss',
      title: t('tutorial:steps.stopLoss.title'),
      description: t('tutorial:steps.stopLoss.description'),
      target: '[data-tutorial="stop-loss"]',
      position: 'top',
      example: t('tutorial:steps.stopLoss.example'),
    },
    {
      id: 'tp1',
      title: t('tutorial:steps.tp1.title'),
      description: t('tutorial:steps.tp1.description'),
      target: '[data-tutorial="tp1"]',
      position: 'top',
      example: t('tutorial:steps.tp1.example'),
    },
    {
      id: 'tp2',
      title: t('tutorial:steps.tp2.title'),
      description: t('tutorial:steps.tp2.description'),
      target: '[data-tutorial="tp2"]',
      position: 'top',
    },
    {
      id: 'tp3',
      title: t('tutorial:steps.tp3.title'),
      description: t('tutorial:steps.tp3.description'),
      target: '[data-tutorial="tp3"]',
      position: 'top',
      example: t('tutorial:steps.tp3.example'),
    },
    {
      id: 'preview',
      title: t('tutorial:steps.preview.title'),
      description: t('tutorial:steps.preview.description'),
      target: '[data-tutorial="preview"]',
      position: 'top',
      example: t('tutorial:steps.preview.example'),
    },
    {
      id: 'submit',
      title: t('tutorial:steps.submit.title'),
      description: t('tutorial:steps.submit.description'),
      target: '[data-tutorial="submit"]',
      position: 'top',
    },
    {
      id: 'positions',
      title: t('tutorial:steps.positions.title'),
      description: t('tutorial:steps.positions.description'),
      target: '[data-tutorial="positions"]',
      position: 'top',
      example: t('tutorial:steps.positions.example'),
    },
    {
      id: 'liquidation',
      title: t('tutorial:steps.liquidation.title'),
      description: t('tutorial:steps.liquidation.description'),
      target: '[data-tutorial="preview"]',
      position: 'top',
      example: t('tutorial:steps.liquidation.example'),
    },
    {
      id: 'history',
      title: t('tutorial:steps.history.title'),
      description: t('tutorial:steps.history.description'),
      target: '[data-tutorial="history-tab"]',
      position: 'bottom',
    },
    {
      id: 'portfolio',
      title: t('tutorial:steps.portfolio.title'),
      description: t('tutorial:steps.portfolio.description'),
      target: '[data-tutorial="portfolio"]',
      position: 'top',
      example: t('tutorial:steps.portfolio.example'),
    },
    {
      id: 'risk-management',
      title: t('tutorial:steps.riskManagement.title'),
      description: t('tutorial:steps.riskManagement.description'),
      target: '[data-tutorial="header"]',
      position: 'bottom',
      example: t('tutorial:steps.riskManagement.example'),
    },
    {
      id: 'finish',
      title: t('tutorial:steps.finish.title'),
      description: t('tutorial:steps.finish.description'),
      target: '[data-tutorial="header"]',
      position: 'bottom',
    },
  ]
}
